<a href="https://colab.research.google.com/github/viperact/pythondemo/blob/main/101_%ED%8C%8C%EC%9D%BC_read_write.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# 구글 드라이브 연동
from google.colab import drive
drive.mount('/content/dirve')

%cd /content/dirve/MyDrive/python_demo

Drive already mounted at /content/dirve; to attempt to forcibly remount, call drive.mount("/content/dirve", force_remount=True).
/content/dirve/MyDrive/python_demo


In [7]:
!pwd

/content/dirve/MyDrive/python_demo


In [9]:
%%writefile ./gosu.txt
hello
안녕

Writing ./gosu.txt


In [10]:
open('./gosu.txt')

<_io.TextIOWrapper name='./gosu.txt' mode='r' encoding='UTF-8'>

###  1.python
open('파일경로', '모드')
- 모드
  - w : 쓰기모드 - 파일에 내용을 쓸때 사용
  - r : 읽기모드 - 파일에 내용을 읽을 때 사용
  - a : 추가모드 - 파일에 내용을 추가할 때 사용

- 파일의 형태 2가지
 - 사람기준(txt)
 - 기계기준(binary)

In [32]:
# 'wb'는 write + binary의 줄임표현이다.
# 쓰기모드로 파일을 불러오며, binary로 저장한다는 의미이다.
a = open('./gosu2.txt', 'wb')

In [33]:
# 'hello'의 타입은 'str'이므로 저장할 수 없다. 왜냐하면 binary로 설정이 되어있기 때문이다.
a.write('hello')

TypeError: ignored

In [34]:
a.write(b'hello')

5

In [35]:
a.close()

###저장한 gosu2.txt파일을 읽어오기

In [38]:
b = open('./gosu2.txt')

In [39]:
next(b)

'hello'

In [24]:
b.close()

### With
- with 구문은 시작할때 enter, 종료할때 __exit를 자동으로 실행해준다.  
- exit가 실행되었기 때문에 close()를 안해준다.
- write가 끝나 후 write()하면 'write to closed file' 에러가 발생한다

In [40]:
with open('./gosu3.txt', 'wb') as c:
  c.write(b'aaa')
  c.write(b'bbb')

In [43]:
# 이미 close 상태이기 때문에 파일에 쓸 수 없다는 오류 발생
# ValueError: write to closed file
c.write(b'ccc')

ValueError: ignored

In [46]:
with open('./gosu3.txt') as c:
  print(c.read())

aaabbb


### 2. numpy
numpy 자체적으로 저장과 불러오는 기능을 지원한다.

In [47]:
import numpy as np

In [48]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

numpy의 데이터를 파일에 저장한다

In [50]:
# ndata1.npy로 저장된다
# array객체 하나는 save()로 저장할 수 있다.
# 확장자는 자동으로 npy가 붙는다.
np.save('./ndata1', a)

numpy의 파일을 읽어온다.

In [52]:
# 읽어올 때는 npy확장자를 붙여서 읽어와야 한다.
# b = np.load('./ndata1') 확장자 없이 불러오면 오류가 발생한다.
b = np.load('./ndata1.npy')
b

array([0, 1, 2, 3, 4])

savez는 array 여러개를 저장할 수 있다.  
확장자는 자동으로 .npz가 붙는다.

In [69]:
b = np.array([1, 2, 3, 4, 5])
c = np.array([6, 7, 8, 9, 10])

In [70]:
np.savez('./ndata2', b, c)

In [71]:
d = np.load('./ndata2.npz')
d

In [72]:
print(dir(d))

['__abstractmethods__', '__class__', '__contains__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_files', 'allow_pickle', 'close', 'f', 'fid', 'files', 'get', 'items', 'iteritems', 'iterkeys', 'keys', 'pickle_kwargs', 'values', 'zip']


dict 방식으로 저장된 객체를 가져올 수 있다.

In [73]:
d.files

['arr_0', 'arr_1']

In [75]:
print(d['arr_0'])
print(d['arr_1'])


[1 2 3 4 5]
[ 6  7  8  9 10]


### 3. pandas

In [76]:
import pandas as pd

In [78]:
num = np.array([[1, 2, 3], [4, 5, 6]])
my_df = pd.DataFrame(num)
my_df

0  1  2
0  1  2  3
1  4  5  6

In [85]:
# pandas에 데이터 저장
my_df.to_csv('./ndata.csv', sep = ',')

In [88]:
# pandas에서 데이터 읽어오기
a = pd.read_csv('./ndata.csv' )
a

Unnamed: 0  0  1  2
0           0  1  2  3
1           1  4  5  6