<a href="https://colab.research.google.com/github/viperact/pythondemo/blob/main/python_09(2)_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### (6) 3차원 이상에서 차원 구분법

In [ ]:
import numpy as np

In [ ]:
# 0부터 24미만까지 생성
b = np.arange(24).reshape(2,3,4) # 2행 3행4열
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# print하면 array라는 글자는 안보인다.
# 공백은 그대로 보인다. -> 차원 구분 가능
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
b[0,1]

array([4, 5, 6, 7])

In [ ]:
b[1,1]

array([16, 17, 18, 19])

In [ ]:
# 0번째 1행 3열
b[0,1,3]

7

### (7) fancy indexing과 indexing 차이
 - indexing은 원래 차원에서 차원이 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다.

In [ ]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원에서 2차원으로 가져온다.)
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# fancy indexing은 원래 3차원 그대로 가져온다.
b[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
# b[0]은 b[0,:,:]의 단축 표현이다.
b[[0],:,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
# b의 0번쨰 공간, 1번째 행 미만, 열 전체
b[0, :1, :]

array([[0, 1, 2, 3]])

### (8) Ellipsis
...(Ellipsis)은 이후로 모든 것을 의미한다.

In [ ]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
type(...)

ellipsis

In [ ]:
b[0] # 생략기법
b[0,:,:] # slicing 기법
b[0,...] # Ellipsis 기법

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
 # 숫자 1, 5, 9만 가져온다.
b[0,:,1]

array([1, 5, 9])

In [ ]:
# 숫자 1,5,9,3,7,11 가져오기
b[0,:,[1,3]]  # fancy indexing

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [ ]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# 숫자 4, 5, 6, 7, 16, 17, 18, 19 가져오기
b[:,1,:]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
b[:,1:2, :]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [ ]:
# 3, 7, 11, 15, 19, 23 가져오기
b[:, :, -1:] # 슬라이싱 이용. 차원 그대로 가져옴

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [ ]:
b[:, :, -1] # 인덱싱 이용. 차원이 하나 빠져서 가져옴.

array([[ 3,  7, 11],
       [15, 19, 23]])

In [ ]:
b[:,:,[3]] # fancy indexing 이용. 차원 그대로 가져옴.

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [ ]:
c = b[:,:,3] # 인덱싱
c.shape

(2, 3)

In [ ]:
b[...,3]

array([[ 3,  7, 11],
       [15, 19, 23]])

### 줄임표현(...)
출력해야할 데이터 수가 엄청 클 때 보이는 ...은 Ellipsis와 다르다.

In [ ]:
# out에 나오는 ...은 단순히 줄임표현이다.
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [ ]:
np.set_printoptions(edgeitems=6)

In [ ]:
# np.set_printoptions(edgeitems=6)로 설정해주면 ...의 앞, 뒤로 나오는 숫자를 정할 수 있다.
np.arange(100000)

array([    0,     1,     2,     3,     4,     5, ..., 99994, 99995, 99996,
       99997, 99998, 99999])

### (9) 연산
numpy연산의 기본은 두 개의 shape가 같아야 한다.

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.shape

(3, 4)

In [ ]:
b = np.arange(1, 13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b.shape

(3, 4)

numpy는 elementwise로 vectorize연산을 한다.  
vectorize는 데이터의 연산을 일괄적으로 처리하는 기능이다.

In [ ]:
# 같은 위치의 원소끼리 더해준다.(elementwise)
a + b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
# python의 list에서 + 연산자는 elementwise가 아니라 list를 확장시킨다. (연결)
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

numpy는 python함수도 vectorize시키는 기능을 지원한다.

In [ ]:
# python에서 vectorize가 되도록 하고싶을 땐  @np.vectorize을 선언해주면 된다,
@np.vectorize
def plus(a,b):
  return a+b

plus([1,2,3], [4,5,6]) # elementwise ,vectorize

array([5, 7, 9])

In [ ]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b = np.arange(6, 12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a * b # elementwise

array([[ 0,  7, 16],
       [27, 40, 55]])

In [ ]:
# TypeError. python의 list끼리는 곱할 수 없다.
[1,2,3] * [3,4,5]

TypeError: ignored

In [ ]:
type(np.array(3))

numpy.ndarray

In [ ]:
c = np.matrix([[1,2,],[3,4]])
c

matrix([[1, 2],
        [3, 4]])

In [ ]:
type(c)

numpy.matrix

numpy에서는 ndarray이외에 matrix라는 자료형도 존재한다.  
matrix에서는 *연산자는 행렬곱을 의미한다.

In [ ]:
# matrix * matrix = 행렬곱
# [1*1+2*3  1*2+2*4] 
# [3*1+4*3  3*2+4+4]
c * c

matrix([[ 7, 10],
        [15, 22]])

ndarray에서 행렬곱 연산자 @이다.  
python재단에서 numpy를 위해 만들어준 연산자이다.

In [ ]:
a.shape

(2, 3)

In [ ]:
b.shape

(2, 3)

In [ ]:
a @ b

ValueError: ignored

행렬곱을 하기 위해서는 shape가 맞아야 한다.  
T는 transpose(전치)의 약자이다.

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 전치 행렬 : 행과 열을 바꾼다. (T)
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
a @ a.T

array([[ 5, 14],
       [14, 50]])

matrix는 @와 * 모두가 가능하다.

In [ ]:
c * c.T

matrix([[ 5, 11],
        [11, 25]])

In [ ]:
c @ c.T

matrix([[ 5, 11],
        [11, 25]])

행렬곱을 함수방법으로 np.dot()을 사용할 수 있다.

In [ ]:
np.dot(a, a.T)  #ndarray

array([[ 5, 14],
       [14, 50]])

In [ ]:
np.dot(c, c.T) #matrix

matrix([[ 5, 11],
        [11, 25]])

method방법으로도 행렬곱 할 수 있다.  
function방법과 사용하는 방법이 다르므로 주의한다.

In [ ]:
np.dot(a, a.T)  # function 방식

array([[ 5, 14],
       [14, 50]])

In [ ]:
a.dot(a.T)  # method 방식

array([[ 5, 14],
       [14, 50]])

#### 연산  
연산할 땐 shape가 맞아야한다.
1. ndarray - @
2. matrix - @ / *
3. np.dot()  - function 방식
4. a.dot()  - method 방식

### (10) broadcasting
python은 배열과 숫자간에 연산을 할 수 있다.  


In [ ]:
[1,2,3] + 1

TypeError: ignored

#### python의 list 연산시  
[1, 2, 3] + 1 (x)  
[1, 2, 3] + [1, 2, 3] (o) => 연결  
[1, 2, 3] * 1 (o)  => 반복  
[1, 2, 3] * [1, 2, 3] (x)

In [ ]:
a = np.arange(6).reshape(2,3)  # ndarray(배열)
a

numpy.ndarray

In [ ]:
# 각각 요소에 1씩 더해진다.
a + 1

array([[1, 2, 3],
       [4, 5, 6]])

broadcasting이란 모양(shape)이 안맞는데, 특정한 조건에 맞으면 모양을 같게 만들어 연산하는 기능이다.  
위 연산에서 1을 a와 같은 모양으로 만들어준다.  
[[1,1,1],  
 [1,1,1]]

(1) broadcasting이 안되는 경우와 가능한 경우

In [ ]:
a # 2행 3열

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a + np.array([3,4])

ValueError: ignored

In [ ]:
# 열의 개수가 같은 경우 아래로 행을 a의 행의 수와 같게 복사하여 더해준다.
a + np.array([3,4,5])

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
# 행의 개수가 같은 경우 우측으로 열을 a의 열의 수와 같게 복사하여 더해준다.
a + np.array([[3],[4]])

array([[3, 4, 5],
       [7, 8, 9]])

### 11 strides
strides는 다음 원소끼리의 메모리 크기를 차원별로 알려준다.  
c의 포인터 개념을 알고 있으면 이해하기가 쉽다.

In [ ]:
a = np.arange(12).reshape(3, 4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 행의 메모리 간격은 32bytes
# 열의 메모리 간격은 8bytes
a.strides

(32, 8)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
# 열의 원소개수 * itemsize = 행의 메모리 간격
# itemsize = 열의 메모리 간격
a.shape

(3, 4)

### 12 axis
axis는 다차원 배열을 연산할 때 기준이 되는 축이다.

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.sum(a)

66

(0,0), (0,1), (0,2), (0,3)  
(1,0), (1,1), (1,2), (1,3)  
(2,0), (2,1), (2,2), (2,3)  

In [ ]:
np.sum(a, axis=0) # a 배열은 2차원이므로 axis=0은 행기준(행마다) - 각 행의 같은 열끼리 더한다.

array([12, 15, 18, 21])

In [ ]:
np.sum(a, axis=1) # a 배열은 2차원이므로 axis=1은 열기준(열마다) - 각 행의 열의 값을 더한다.

array([ 6, 22, 38])

axis는 3차원 이상에서도 사용할 수 있다. 

In [ ]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(0,0,0)(0,0,1)(0,0,2)(0,0,3)  
(0,1,0)(0,1,1)(0,1,2)(0,1,3)  
(0,2,0)(0,2,1)(0,2,2)(0,2,3)  
  
(1,0,0)(1,0,1)(1,0,2)(1,0,3)  
(1,1,0)(1,1,1)(1,1,2)(1,1,3)  
(1,2,0)(1,2,1)(1,2,2)(1,2,3)  

In [ ]:
# a.sum(axis=0)
# 공간의기준으로 (공간마다) - 각 공간의 행과 열이 같은 것끼리 더한다. 
# 즉, 공간은 다르고 행과 열이 같은 것끼리 더해진다.
# ex) (0,0,0) (1,0,0) 끼리 더해진다.
np.sum(a, axis=0)  # 함수이용
# a.sum(axis=0) # 메소드이용

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
# 행의기준으로 (행마다) - 같은 공간의 각 행의 같은 열끼리 더한다. 
# 즉, 공간과 열은 같고 행이 다른 것끼리 더해진다.
# ex) (0,0,0) (0,1,0) (0,2,0) 끼리 더해진다. 
np.sum(a, axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [ ]:
# 열의기준으로 (열마다) - 같은 공간의 각 행끼리 더한다.
# 즉, 공간과 행은 같고 열이 다른 것끼리 더해진다.
# ex) (0,0,0) (0,0,1) (0,0,2) (0,0,3) 끼리 더해진다.
np.sum(a, axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

3차원은 행렬에 공간(깊이)개념이 추가되었다고 할 수 있다.  
2차원(axis=0,axis=1)(행,열)  
3차원(axis=0,axis=1,axis=2)(공간,행,열)

### (12) array 모양 바꾸기

(1) reshape  
  reshape는 차원을 바꿔주는 기능을 한다.

In [ ]:
# signature대로 하면 a.reshape((3,8)) 해야한다.
# 하지만 reshape(3,8)해도 내부적으로 이상없이 처리한다.
# reshape 수행 후의 원래의 값은 그대로 있다.
a = np.arange(24)
b = a.reshape(3,8)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
# ValueError => 크기가 맞지 않음.
a.reshape(2,3,5)

ValueError: ignored

In [ ]:
# 음수를 쓰면 알아서 shape를 맞춘다.
# 음수 값은 -1이든, -100이든 상관없이 음수이기만 하면 된다.
a.reshape(2,3,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# 단, 공간과 행의 값이 크기의 계산이 될 수 있게 해줘야한다.
# ValueError
a.reshape(3,5,-1)

ValueError: ignored

In [ ]:
# 음수를 2개 사용할 수 없다.
# 음수는 다른 차원들이 정해준 상황에서 남은 하나의 차원만 알아서 맞춰준다.
a.reshape(3,-1,-1)

ValueError: ignored

In [ ]:
# 음수값이 1개이면 위치가 어디에 오든 상관없다.
a.reshape(3,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

(2) reshpae 으로 차원 늘리기

In [ ]:
# 2차원
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 3차원
a = np.arange(6).reshape(2,3,1)
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

### (13) resize
size는 원소 개수를 알려준다. 

In [ ]:
a = np.arange(24)
# 원소의 개수
print(a.size)
print(len(a))

24
24


In [ ]:
# a.resize(2,3,1)
np.resize(a, (2,3,1))

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
# reshape은 원소의 개수가 맞아야 변경 가능하지만, resize는 원소의 개수가 다르면 원소를 채워 변경한다.
# 함수를 이용하면 빈 공간을 원래 있는 값을 반복하여 채워준다.
np.resize(a, (3,2,8))

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]])

In [ ]:
# mutable이다. return이 없고 자기 자신을 바꾼다. -> reshape와 차이점 1
# 원래의 원소 개수와 변경하는 원소 개수가 안맞아도 된다.(0으로 채워준다.) -> reshape와 차이점 2

b = np.arange(24)
b.resize(2,3,8) # resize의 return값은 none이다.
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])

### (14) array 쪼개기


split

In [ ]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# a는 바뀌지 않으므로 재할당을 한다.
a = np.split(a, 3, axis=0)
a

[array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21, 22, 23])]

In [ ]:
print(type(a))
print(type(a[0]))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
b = np.arange(24)
b = np.split(b,2)
b

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [ ]:
print(type(b))
print(type(b[1]))
print(b[1])
print(b[1][2])
# print(b[1,2]) # TypeError, 배열이 아닌 리스트이기때문에 오류가 생긴다.

c = np.array(b)
print(c)
print(type(c))
print(c[1,2])

<class 'list'>
<class 'numpy.ndarray'>
[12 13 14 15 16 17 18 19 20 21 22 23]
14
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
<class 'numpy.ndarray'>
14


#### hsplit & vsplit
http://taewan.kim/post/numpy_cheat_sheet/ 참고사이트

split는 axis 파라미터가 있다. default: axis=0

In [ ]:
a = np.arange(24)
b = a.reshape(4,6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
# split로 나누면 list로 가져온다.
# 행단위로 나눠진다.
np.split(b, 2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
 np.split(b, 2, axis=1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [ ]:
# 차원을 하나로 가져온다.
np.hsplit(a,2) # horizental (수평)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [ ]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

(0,0), (0,1), (0,2), (0,3)  (0,4)  
(1,0), (1,1), (1,2), (1,3)  (1,4)  
(2,0), (2,1), (2,2), (2,3)  (2,4)  
(3,0), (3,1), (3,2), (3,3)  (3,4)

In [ ]:
# vsplit은 1차원일 때 ValueError가 발생한다.
np.vsplit(b,2) # 2차원일 때 : Vertical(수직)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
np.hsplit(b,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

#### indices_or_sections
split 시리즈 함수들의 두번째 파라미터 이름이 indices_or_section이다.  
숫자를 묶어서 넣으면 구간으로 쪼개진다.

In [ ]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# section
# 처음부터 ~ 2 미만:[0,1]
# 2부터 ~ 3 미만: [2]
# 3부터 ~ 끝까지: [3,4,5, ..., 23]
np.hsplit(a, (2,3))

[array([0, 1]),
 array([2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23])]

In [ ]:
# section
# 처음부터 ~ 2 미만:[0,1]
# 2부터 ~ 3 미만: [2]
# 3부터 ~ 8 미만: [3,4,5,6,7]
# 8부터 ~ 끝까지: [8,9,10,...,23]
np.hsplit(a, (2,3,8))

[array([0, 1]),
 array([2]),
 array([3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

### (15) array 합치기

In [ ]:
a = np.arange(24)
x, y, z = np.split(a, 3)

In [ ]:
print(x)
print(y)
print(z)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


#### hstack & vstack

In [ ]:
# hstack은 horizental(가로)로 합쳐준다.
# 1차원끼리 합치면 1차원으로 합쳐진다.
np.hstack((x, y))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# vstack은 vertical(세로)로 합쳐준다.
# 1차원끼리 합치면 2차원으로 합쳐진다.
np.vstack((x, y))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

#### dstack
dstack는 합쳐서 3차원으로 만들어준다.  
합칠 array들이 1차원, 2차원일 경우는 차원을 늘리 후 합친다.  
합쳐지는 차원은 axis=2 이다.

In [ ]:
print(x)
print(y)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]


In [ ]:
# x는 shape 1차원이므로 (1, m, 1)인 3차원으로 변환한다.
# y는 shpae 1차원이므로 (1, m, 1)인 3차원으로 변환한다.
# 합쳐지는 차원은 axis=2이다.
c = np.dstack((x, y)) # (1,8,2)
c

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11],
        [ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [ ]:
# x.shape
c.shape

(1, 8, 2)

#### concatenate
concatenate는 axis방향에 그대로 합쳐준다.  
※ stack은 axis방향에 새로운 차원을 만들어 합쳐준다.

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
x, y = np.split(a, 2, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(x)
print(y)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [ ]:
# 원래 shape 크기 그대로 유지를 한다.
np.concatenate((x,y))

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
# shape 크기를 1개 증가해서 합친다.
np.stack((x,y))

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

### (16) 차원 확장
numpy는 차원을 확장하는 여러가지 방법이 있다.

reshape

In [ ]:
# np.arange(12) : 1차원
# reshape(3,4) : 2차원
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

stack

In [ ]:
# 3차원으로 확장
# tuple에 원소가 1개 있으면 차원만 확장시켜준다.
np.stack((a,))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

newaxis  
- 인덱싱할 때 np.newaxis를 쓰면 차원을 늘릴 수 있다.(인덱스 자리에 넣어주면 된다.)

In [ ]:
# 2차원
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.shape

(3, 4)

In [ ]:
# 3차원
# a[np.newaxis] 와 같다.
a[np.newaxis,:,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
a[np.newaxis].shape

(1, 3, 4)

In [ ]:
# asix처럼 숫자를 대입하면 오류가 난다.
a[np.newaxis=0]

SyntaxError: ignored

In [ ]:
a[:,np.newaxis,:]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [ ]:
a[:,np.newaxis,:].shape

(3, 1, 4)

In [ ]:
a[:,:,np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [ ]:
a[:,:,np.newaxis].shape

(3, 4, 1)

In [ ]:
np.newaxis is None

True

np.newaxis 대신에 None을 써도 된다.  
None은 직관적이지 않고 헷갈려서 np.newaxis를 만들었다.  
numpy를 만들 때 python의 모든 연산자를 다 사용해서 남는 연산자가 없었다. 그래서 None를 이용했다.

In [ ]:
a[:,None,:]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.expand_dims(a, 0) # a[np.newaxis, :, :]와 같다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
a[np.newaxis, :, :]  #a[np.newaxis]와 같다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
np.expand_dims(a, 1) # a[:, np.newaxis, :]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [ ]:
np.expand_dims(a, 2) #a[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

### (17) array 한줄로 펴기

flatten

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# flatten()은 결과를 return하고 메모리의 값은 변경되지않는다. 
# 1차원으로 만들어준다.
b = a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### (18) 서로 차원 교환

axes = axis의 복수  
swapaxes

In [ ]:
a = np.array([[1],[2]]) # 2차원 2행 1열

In [ ]:
a

array([[1],
       [2]])

In [ ]:
a.shape

(2, 1)

In [ ]:
# a의 0번 차원과 1번 차원을 서로 바꾼다.
b = np.swapaxes(a,1,0)

In [ ]:
b

array([[1, 2]])

In [ ]:
a.T

array([[1, 2]])